### ISSUE TITLE
ラベルのテキストをプログラムから変更

### ISSUE THREAD

**Issue by ryotaman** [ttakeda/ios_learning#3]
FirstViewControllerのUILabelをFristViewController.swiftから変更する
IBOutlet 宣言を利用して プログラム内から内容を上書きして下さい

実装が出来たらPUSH後にコメントして下さい。

**Comment by ttakeda** [comment]
こちら実装してみました。
なお、ViewControllerの名前を分かりやすいよう、以下に変更してしまったのですが問題ないでしょうか？
- FirstViewController -> FacebookViewController
- SecondViewController -> TwitterViewController
- ThirdViewController -> SettingViewController

ご確認の程、よろしくお願い致します。
212cc2b

**Comment by ryotaman** [comment]
はい。ファイル名の変更問題ありません。
storybordとの連携もできていたので素晴らしいです！ :+1: 
テキストの内容も上書きできていました！

テキスト内容をUILabelの範囲以上入力した時の挙動や、
改行した時のにどうなるか試してみてください。

**Comment by ttakeda** [comment]
ご確認ありがとうございます！
承知いたしました。
色々と挙動を確認してみるようにします。

**Comment by ttakeda** [comment]
テキストの内容が範囲を超えても適度に表示されるよう調整してみました。
ご確認の程、よろしくお願い致します。

**Comment by ryotaman** [comment]
領域に収まるようになっていることが確認出来ました！ :+1:
