### ISSUE TITLE
TextFieldの配置

### ISSUE THREAD

**Issue by ryotaman** [ttakeda/ios_learning#4]
StoryBordのFirstViewController 内にTextFieldを配置し、
常に中央になるようオートレイアウトを設定

* TextFieldの表示サイズを変更
* 高さを変更

実装が出来たらPUSH後にコメントして下さい。

**Comment by ttakeda** [comment]
こちら実装してみました。
ご確認の程、よろしくお願い致します。
77781f7

**Comment by ryotaman** [comment]
実装確認出来ました　:+1:
