### ISSUE TITLE
TextField内容をUILabelに反映

### ISSUE THREAD

**Issue by ryotaman** [ttakeda/ios_learning#5]
FirstViewController.swiftで
TextFieldに入力された文字を先ほど設定したUILabelにリアルタイムに反映させる

実装が出来たらPUSH後にコメントして下さい。

**Comment by ttakeda** [comment]
こちら実装してみました。
ご確認の程、よろしくお願い致します。
c8c3dea

**Comment by ryotaman** [comment]
delegateメソッドを利用して簡潔に書いてありとても良いです :smile:
