### ISSUE TITLE
TextFieldのキーボード閉じ

### ISSUE THREAD

**Issue by ryotaman** [ttakeda/ios_learning#6]
TextFieldをタップ時に出現するキーボードを
完了ボタン（確定、done等）がタップされた時にキーボードをしまう

実装が出来たらPUSH後にコメントして下さい。

**Comment by ttakeda** [comment]
こちら実装してみました。
ご確認の程、よろしくお願い致します。
51df326

**Comment by ryotaman** [comment]
リターンキーで閉じられること確認出来ました :+1:
